version: '3'
services:
    mysql:
        image: mysql:5.5
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root     
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=dolibarr
        volumes:
            - ./data/db/mysql:/var/lib/mysql

    dolibarr:
        build: .
        ports:
            - "1234:80"
        depends_on:
            - mysql
        links: 
            - mysql
        volumes:
            - dolibarr-data:/var/www/html
volumes:
  dolibarr-data:
    driver: local
